global:
 resolve_timeout: 1m

route:
 receiver: 'email-notifications'

receivers:
- name: 'email-notifications'
  email_configs:
  - to: servicedeskcmcts@gmail.com
    from: servicedeskcmcts@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: servicedeskcmcts@gmail.com
    auth_identity: servicedeskcmcts@gmail.com
    auth_password: Viettel@123
    send_resolved: true
    require_tls: false
